/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tennissportsclubapp;

import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JTable;
import java.awt.PrintGraphics;
import java.text.*;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Tshegofatso
 */
public class frmViewMembers extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmViewMembers
     */
    public frmViewMembers() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User> userList()
    {ArrayList <User> usersList = new ArrayList<>();

String strDBConnectionString="jdbc:mysql://localhost:3306/tennissportsclubapp";
String strDBUser="root";
String strDBPassword="Password";
java.sql.Connection conMySQLConnectionString;
Statement stStatement=null;
ResultSet rs= null;

try
{
conMySQLConnectionString=DriverManager.getConnection(strDBConnectionString,strDBUser,strDBPassword);
stStatement = conMySQLConnectionString.createStatement();
String strQuery = " Select * from Members";
stStatement.execute(strQuery);
rs=stStatement.getResultSet();
User user;

while(rs.next())
{
user=new User(rs.getInt("ID"), rs.getString("MemberName"), rs.getString("Username"), rs.getString("UsernamePassword"), rs.getString("Role"), rs.getString("ContactNumber"), rs.getString("Address"), rs.getString("NextOfKin"), rs.getString("Sex"), rs.getString("DateOfBirth"), rs.getString("Membership"), rs.getString("PersonalTrainer"), rs.getString("TimeSelected") );
usersList.add(user);
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e);
}

return usersList;
    }

public void show_user()
{
    ArrayList<User> list = userList();
    DefaultTableModel model = (DefaultTableModel) jtMembersTable.getModel();
Object[] row = new Object[13];
for(int i=0;i<list.size();i++)
{
row[0]=list.get(i).getID();
row[1]=list.get(i).getMemberName();
row[2]=list.get(i).getUsername();
row[3]=list.get(i).getUsernamePassword();
row[4]=list.get(i).getRole();
row[5]=list.get(i).getContactNumber();
row[6]=list.get(i).getAddress();
row[7]=list.get(i).getNextOfKin();
row[8]=list.get(i).getSex();
row[9]=list.get(i).getDateOfBirth();
row[10]=list.get(i).getMembership();
row[11]=list.get(i).getPersonalTrainer();
row[12]=list.get(i).getTimeSelected();
model.addRow(row);

}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        jpMemberProfileTitle = new javax.swing.JPanel();
        lblMemberProfileTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jtMembersTable = new javax.swing.JTable();
        btnPrintReport = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();

        setTitle("View Members");
        setToolTipText("");

        jpBackground.setBackground(new java.awt.Color(255, 255, 255));
        jpBackground.setToolTipText("");
        jpBackground.setAutoscrolls(true);
        jpBackground.setLayout(null);

        jpMemberProfileTitle.setBackground(new java.awt.Color(0, 204, 0));

        lblMemberProfileTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblMemberProfileTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMemberProfileTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMemberProfileTitle.setText("View Members");
        lblMemberProfileTitle.setToolTipText("");

        javax.swing.GroupLayout jpMemberProfileTitleLayout = new javax.swing.GroupLayout(jpMemberProfileTitle);
        jpMemberProfileTitle.setLayout(jpMemberProfileTitleLayout);
        jpMemberProfileTitleLayout.setHorizontalGroup(
            jpMemberProfileTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemberProfileTitleLayout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(lblMemberProfileTitle)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jpMemberProfileTitleLayout.setVerticalGroup(
            jpMemberProfileTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMemberProfileTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jpBackground.add(jpMemberProfileTitle);
        jpMemberProfileTitle.setBounds(0, 0, 1010, 50);

        jtMembersTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtMembersTable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtMembersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Password", "Role", "ContactNo", "Address", "NextOfKin", "Sex", "DateOfBirth", "Membership", "Trainer", "Time"
            }
        ));
        jtMembersTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtMembersTable.setGridColor(new java.awt.Color(255, 255, 255));
        jtMembersTable.setShowVerticalLines(false);
        jScrollPane.setViewportView(jtMembersTable);

        jpBackground.add(jScrollPane);
        jScrollPane.setBounds(30, 90, 950, 430);

        btnPrintReport.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnPrintReport.setText("Print Report");
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });
        jpBackground.add(btnPrintReport);
        btnPrintReport.setBounds(880, 550, 100, 25);

        btnExit.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jpBackground.add(btnExit);
        btnExit.setBounds(30, 550, 60, 23);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Members List");
        MessageFormat footer = new MessageFormat ("Tennis Sports Club");
        try
        {
            jtMembersTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            JOptionPane.showMessageDialog(null, "Cannot be Printed" +e.getMessage());
        }
    }//GEN-LAST:event_btnPrintReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JPanel jpMemberProfileTitle;
    private javax.swing.JTable jtMembersTable;
    private javax.swing.JLabel lblMemberProfileTitle;
    private javax.swing.JMenuBar mnuMenuBar;
    // End of variables declaration//GEN-END:variables
}
